name: tipcalculator
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

    

  cupertino_icons: ^1.0.6
  webview_flutter: ^4.7.0
  dio: ^5.4.3+1
  http: ^1.2.1
  convert: ^3.1.1
  io: ^1.0.4
  path_provider: ^2.0.9 
  flutter_spinbox: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Regular.otf
  uses-material-design: true
  assets:
    - assets/